set -e
true
true
/usr/libexec/spades/spades-hammer /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/corrected/configs/config.info
/usr/bin/python3 /usr/share/spades/spades_pipeline/scripts/compress_all.py --input_file /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/corrected/corrected.yaml --ext_python_modules_home /usr/share/spades --max_threads 16 --output_dir /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/corrected --gzip_output
true
true
/usr/libexec/spades/spades-core /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/K21/configs/config.info
/usr/libexec/spades/spades-core /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/K33/configs/config.info
/usr/bin/python3 /usr/share/spades/spades_pipeline/scripts/copy_files.py /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/K33/before_rr.fasta /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/before_rr.fasta /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/K33/assembly_graph_after_simplification.gfa /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/assembly_graph_after_simplification.gfa /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/K33/final_contigs.fasta /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/contigs.fasta /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/K33/first_pe_contigs.fasta /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/first_pe_contigs.fasta /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/K33/strain_graph.gfa /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/strain_graph.gfa /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/K33/scaffolds.fasta /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/scaffolds.fasta /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/K33/scaffolds.paths /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/scaffolds.paths /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/K33/assembly_graph_with_scaffolds.gfa /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/assembly_graph_with_scaffolds.gfa /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/K33/assembly_graph.fastg /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/assembly_graph.fastg /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/K33/final_contigs.paths /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/contigs.paths
true
/usr/bin/python3 /usr/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/scaffolds.fasta --misc_dir /mnt/c/Users/deomo/OneDrive/Escritorio/bioinformatica/data/ensamblajeRNAseq_1/misc --threshold_for_breaking_scaffolds 3
true
